name: easyhpv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310ha9d4c09_0
  - bwa=0.7.19=h577a1d6_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - htslib=1.22.1=h566b1c6_0
  - importlib-metadata=8.5.0=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=h46f56fc_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb25bd0a_0
  - natsort=8.4.0=py310h06a4308_0
  - ncls=0.0.70=py310h1fe012e_0
  - ncurses=6.5=h2d0b736_3
  - numexpr=2.11.0=py310hccd6f0b_1
  - numpy=2.0.1=py310heeff2f4_1
  - numpy-base=2.0.1=py310h8a23956_1
  - openjdk=8.0.152=h7b6447c_3
  - openssl=3.5.4=h26f9b46_0
  - pandas=2.3.3=py310h505adc9_0
  - perl=5.26.2=h14c3975_0
  - picard=2.20.4=0
  - pip=25.2=pyh8b19718_0
  - pyranges=0.1.4=pyhdfd78af_0
  - pysam=0.23.3=py310h64e62c9_1
  - python=3.10.19=hd994cfb_1_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=1_cp310
  - pytz=2025.2=py310h06a4308_0
  - readline=8.2=h8c095d6_2
  - samtools=1.22.1=h96c455f_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=py310h06a4308_0
  - sorted_nearest=0.0.41=py310h1fe012e_0
  - tabulate=0.9.0=py310h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zipp=3.21.0=py310h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
